# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd02bf224271eb028e5f936383ac7ccabf9243141567e271d208b6b48c0f258f740bed795da960750690171b91e3380c96f6a8659a13f4976c0872393c09bfe

test:
  secret_key_base: 1eaffcf02c02ed727924306acc623e202ed0d4aa3ae2c2ac534552f7bbfd0613708b3c0e2f10856d134339164a5c392a855a49acc59f78fb641c8de68d627769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
